# Generated by Django 3.1.5 on 2021-08-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20210804_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
