# Generated by Django 3.2.3 on 2021-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20210811_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
